<?php

namespace keltanas\Bundle\TrackingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{
    public function getQueryNoBot()
    {
        return $this->createQueryBuilder('h')
            ->where('h.bot = :bot AND h.utmSource != :source')
            ->setParameter(':bot', 0)
            ->setParameter(':source', 'trafficgen')
            ->orderBy('h.trackingAt', 'desc')
            ->getQuery();
    }

    public function getQueryGroupingByRange(\DateTime $dateFrom = null, \DateTime $dateTo = null)
    {
        $qb = $this->createQueryBuilder('h')
            ->select('h.utmSource, COUNT(h.id) as sourceCount')
            ->where('h.bot = :bot')
            ->setParameter(':bot', 0)
            ->addGroupBy('h.utmSource')
            ;

        if ($dateFrom) {
            $qb->andWhere('h.updatedAt > :dateFrom')->setParameter(':dateFrom', $dateFrom->format('Y-m-d H:i:s'));
        }
        if ($dateTo) {
            $qb->andWhere('h.updatedAt < :dateTo')->setParameter(':dateTo', $dateTo->format('Y-m-d H:i:s'));
        }

        return $qb->getQuery();
    }
}
